### PR TITLE
Mention ChanReader/ChanWriter will be unstable

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by aturon** [comment]
Hm, what's the rationale here? Just that we may want to tweak their behavior?

**Comment by alexcrichton** [comment]
Our channel story has undergone some interesting shifts recently (everything has moved to `std::sync::mpsc` for example) and I'm not sure how these would play into multiple flavors of channels provided by `std::sync`. 

These types also aren't necessarily that efficient as they're allocating all writes onto the heap to send across tags. An in-memory reader/writer pair would probably be much more efficient with cvars/mutexes if possible.

In general I think I'm just a little uneasy stabilizing these types. They're not the most useful things in the world, they're a little unergnomic to construct, and they seem like they're from an era of "channels for everything" which has since passed.

**Comment by aturon** [comment]
Ok. Mind adding a bit of that text to the diff here?

**Comment by alexcrichton** [comment]
Done!

**Pull request merged**
