### PR TITLE
some revisions for docs section of the roadmap

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by steveklabnik** [comment]
r? rust-lang/docs (I've sent this to the team, let's have them look it over before a merge)

**Comment by aturon** [comment]
The content LGTM. However, note that the section you're editing is a subsection under the Epoch 2018 plan, but you're touching on *all* the roadmap items here.

**Comment by steveklabnik** [comment]
ah, oops!

**Comment by steveklabnik** [comment]
okay, so looking at the rest of the document, the non-epoch goals don't really have summaries for each team. So I've pushed one more commit to just update this bit, let's :shipit:

**Comment by aturon** [comment]
Merged, thanks @steveklabnik!

**Pull request merged**
